#!/usr/bin/env bash
# All pages have been scanned, time to enhance them for OCR and concat them to
# a single PDF file

TMPDIR="/tmp"
HOLDINGDIR="$(dbus-uuidgen)"
SCANNEDFILES="scan_*.pnm"
CLEANEDDIR="$TMPDIR/$HOLDINGDIR/cleaned"
LOGFILE="/var/log/insaned.log"
PDFFILE="$TMPDIR/$HOLDINGDIR/$(date "+%Y%m%d_%H%M%S").pdf"
SCANSDIR="/scans"
LOCKFILE="$TMPDIR/extra.lock"

echo "$(date) | extra: button pressed, assembling $TMPDIR/$SCANNEDFILES into $PDFFILE..." >> "$LOGFILE"

if [ -f $LOCKFILE ]; then
  echo "$(date) | extra: ERROR, another assembling operation is in progress (id: $(cat "$LOCKFILE"))" >> $LOGFILE
  exit 0
fi

mkdir -p "$CLEANEDDIR"

# we'll run the conversion as a background job, we need to move the pages to a
# separate dir so they don't get mixed up with the next scan

# shellcheck disable=SC2086
# the glob must be expanded
mv $TMPDIR/$SCANNEDFILES "$TMPDIR/$HOLDINGDIR"

echo "$HOLDINGDIR" >> "$LOCKFILE"

{
  # textcleaner can only process single pages
  for tmpfile in $TMPDIR/$HOLDINGDIR/$SCANNEDFILES
  do

    echo "$(date) | extra: cleaning $tmpfile..." >> "$LOGFILE"
    textcleaner -g "$tmpfile" "$CLEANEDDIR/$(basename "$tmpfile")" &&\
    echo "$(date) | extra: moving cleaned file $tmpfile to $CLEANEDDIR/$(basename "$tmpfile")..." >> "$LOGFILE" &&\
    rm "$tmpfile"
  done
   
  convert "$CLEANEDDIR/*.pnm" "$PDFFILE" &&\
  echo "$(date) | extra: PDF file saved to $PDFFILE" >> "$LOGFILE" &&\
  mv "$PDFFILE" "$SCANSDIR" &&\
  echo "$(date) | extra: moved $PDFFILE to $SCANSDIR" >> "$LOGFILE" &&\
  rm -rf "${TMPDIR:?}/$HOLDINGDIR"
  rm "$LOCKFILE"
} &
