#!/usr/bin/env bash

# exit when a command doesn't exit with 0
set -euo pipefail

out_file="/tmp/scan_$(date "+%Y%m%d_%H%M%S").pnm"
log_file="/var/log/insaned.log"
event_name="file"
paper_width="215.9" # mm
paper_height="279.4" # mm
orientation=${PAGE_ORIENTATION:-portrait}
batch_mode=${BATCH_MODE:-false}

handle_exit() {
  exit_code="$1"

  if [ "$exit_code" -ne 0 ]
  then
    log_message "something went wrong :("
    exit 1
  else
    exit 0
  fi
}

trap 'handle_exit $?' EXIT

log_message() {
  default_message="no message passed to logging function"

  echo "$(date) | $event_name: ${1-$default_message}" >> "$log_file"
}

scan() {
  scanimage \
    --resolution 300 \
    --mode gray \
    -x "$paper_width" \
    -y "$paper_height" \
  > "$out_file"
}

rotate() {
  if [[ $orientation = l ]]
  then
    log_message "landscape page, rotating..."
    convert -rotate 90 "$out_file" "$out_file-rot"
    rm "$out_file"
    mv "$out_file-rot" "$out_file"
    log_message "page rotated"
  fi
}

main() {
  log_message "button pressed, saving page to $out_file"
  log_message "options: orientation=$orientation, batch_mode=$batch_mode"
  scan
  rotate
  log_message "page saved to $out_file"
}

# Redirect errors to logfile
main 2>>"$log_file"
